### ISSUE TITLE
Unable to deconstruct...

### ISSUE THREAD

**Issue by frevenstanks** [klangzwang/MoarFactory#16]
Hello
I've built the AGP but now I cant seem to deconstruct it? Also the "E" menu doesn't appear.
Experimental Build #124884
Please let me know if you need more info.
Thank You!

**Comment by frevenstanks** [comment]
![image](https://user-images.githubusercontent.com/67107099/85024224-bc7bc100-b16d-11ea-947a-04d09ed5ca47.png)
Apologies. 
AGP can be deconstructed but only by aiming on the area around the foot, highlighted in the screenshot. Also the yellow and black stripes flicker in game.
"E" menu still not working even if aimed at foot area.

**Comment by rcamarda390** [comment]
E does not work for me either.

**Comment by rcamarda390** [comment]
Not quite sure what the AGP is for :)

**Comment by yesod-github** [comment]
> Apologies.
> AGP can be deconstructed but only by aiming on the area around the foot, highlighted in the screenshot. Also the yellow and 

Thanks for the update :)
