### ISSUE TITLE
Input and Output ports switched on Storage

### ISSUE THREAD

**Issue by rcamarda390** [klangzwang/MoarFactory#17]
Something weird is going on with the input/output of large storage containers. (glad to see the images are back for the ports on storage!)
I tried to add a belt to an existing Teleporter (mod) and storage. 
See below image showing what I had after update, 1.1.0. (out connected to out).
![image](https://user-images.githubusercontent.com/51367321/85041136-8895a100-b157-11ea-8f59-0642ed7414c5.png)

I think the ports have been flipped, what was in is now out.

I installed 1.0.9 and belts are work again

![image](https://user-images.githubusercontent.com/51367321/85042441-35bce900-b159-11ea-8afa-c8600c64a145.png)

**Comment by yesod-github** [comment]
Fixed as-of v1.1.3.
_Thanks for reporting._
