### ISSUE TITLE
[MF v.1.0.5; SF-EA 118201] Foundation04, Foundation05: Transparency.

### ISSUE THREAD

**Issue by yesod-github** [klangzwang/MoarFactory#2]
![Screenshot20200423-15385200000_042320_034023_PM](https://user-images.githubusercontent.com/26621448/80142258-ddae9f80-8578-11ea-9fc5-bc7132af8d51.jpg)

![Screenshot20200423-15364700000_042320_033952_PM](https://user-images.githubusercontent.com/26621448/80142206-ca9bcf80-8578-11ea-8825-678bb2807a5f.jpg)

Question marks because not sure intent of asset. Nonetheless, kindly consider to implement both versions; one with grate and one without as both options are very versatile!

**Comment by yesod** [comment]
Fixed in v1.1.0.

**Comment by yesod-github** [comment]
Fixed in v1.1.0.
