### ISSUE TITLE
Flying creates shudder movement for second player in multiplayer

### ISSUE THREAD

**Issue by duganm** [klangzwang/MoarFactory#21]
Hello,

I'm joining a friend of mine's server where he is hosting, and I've applied the same mods that he has in place. The list of mods are: MoarFactory, MoarAssets, MoarDevice. When I activate the fly mode while holding the tablet, I experience "shudder" movement, essentially up and down motions, and cannot fly at all...but the host is still able to fly around in the server.

**Comment by yesod-github** [comment]
Install [PakUtility](https://ficsit.app/mod/6nKYZmGkoJmx9Z). In game, disable MoarTablet flight. Enter command `!fly medium` then toogle flight mode via `!fly`. Report back whether the same experience exist.

**Comment by duganm** [comment]
That did it, thank you!
